apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ephemeral-namespace-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/psavage-tenant/ephemeral-namespace-operator/ephemeral-namespace-operator@sha256:d413d32556d7888324398249108dd96c9f4f8067b9b3901b5dc90bf569655ec7
        name: container-image
        resources: {}
status: {}
